# application.yaml 파일은 application.properties 파일과 같은 역할을 한다.
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet:
    multipart:
      file-size-threshold: 80MB
      max-request-size: 80MB

  datasource:
    # H2 Database
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

server:
  port: 8080




# System properties 통합
james:
  host: localhost
  admin:
    port: ${JAMES_WEB_ADMIN_PORT:8000}

file:
  upload_folder: /WEB-INF/upload
  download_folder: /WEB-INF/download
  max_size: 52428800
